
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanata-backend
    restart: always
    ports:
      - "3435:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs
    networks:
      - backend-network


networks:
  backend-network:
    driver: bridge
